#config_version=6

# NOTE: this is needed for the unittests which expect
#       the main config file to be named config.yaml.
config:
- development.yaml
# - production_linux.yaml
# - production_macos.yaml
