#config_version=6
ball_devices:
  bd_trough:
    ball_switches:
    - s_trough1
    - s_trough2
    - s_trough3
    tags:
    - trough
    - home
    - drain
    eject_timeouts: 1s
    eject_coil: c_trough_eject
    eject_targets: bd_shooter_lane
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    ball_search_order: 3
    debug: true
  bd_shooter_lane:
    ball_switches: s_shooter_lane
    mechanical_eject: true
    eject_timeouts: 3s
